name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/SnooSharp.sln
    - name: Build
      run: dotnet build src/SnooSharp.sln --no-restore
    - name: Test
      run: dotnet test src/SnooSharp.sln --no-build --verbosity normal
